# Generated by Django 3.2 on 2021-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20210525_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='heading',
            new_name='header',
        ),
    ]
