# Generated by Django 3.2 on 2021-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='check_edit',
            field=models.BooleanField(default=False),
        ),
    ]
