# Generated by Django 3.2 on 2023-03-26 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0006_diary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Entry',
        ),
    ]
