# Generated by Django 3.2 on 2023-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0003_alter_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
    ]
