# Generated by Django 3.2 on 2023-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_message_id_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_edited',
            new_name='is_edited',
        ),
    ]
