# Generated by Django 3.2 on 2023-01-20 16:08

import accounts.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationKey',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('key', models.CharField(default=accounts.utils.uuid, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('account_type', models.CharField(default='Standard', max_length=15)),
                ('birthday', models.DateField(blank=True, help_text='Birthday in YYYY-MM-DD format [used for displaying age].', null=True)),
                ('location', models.CharField(blank=True, help_text='Geographic location.', max_length=40)),
                ('website', models.URLField(blank=True, help_text='A personal blog or website.')),
                ('bio', models.TextField(blank=True, help_text='A brief biography.', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar/')),
            ],
            options={
                'ordering': ('-user__last_login',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='Standard', max_length=15)),
                ('key', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
