# Generated by Django 3.1.4 on 2021-01-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='recipient',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
