# Generated by Django 3.1.4 on 2021-02-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210118_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
